name: Generate Notebooks
on:
  push:
    paths:
      - '*.py'
      - '!*.ipynb'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install nbformat
      - run: python notebook_generator.py
      - name: Commit notebooks
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.ipynb
          git commit -m "Auto-generate notebooks" || exit 0
          git push 