name: main
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'notebook_generator.py'
      - '.github/workflows/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat
      
      # Generate notebooks
      - name: Generate notebooks
        run: python notebook_generator.py
      
      # Switch to publish branch and update notebooks
      - name: Commit to publish branch
        run: |
          # Save the readme content and notebooks before switching branches
          cp .github/publish-readme.md /tmp/publish-readme.md
          cp -r notebooks /tmp/notebooks
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin publish || git checkout --orphan publish
          git checkout publish || git checkout --orphan publish
          
          # Clean the branch but keep .git directory
          git rm -rf .
          
          # Copy saved files back
          cp /tmp/publish-readme.md README.md
          cp -r /tmp/notebooks .
          
          # Commit and push changes
          git add README.md notebooks/
          git commit -m "Update notebooks from main branch" || echo "No changes to commit"
          git push origin publish
